mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  config: classpath:logback-spring.xml

server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
  data:
    mongodb:
      uri: mongodb://localhost:27017/study
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8899
        port: 7080
  application:
    name: simple-springboot-study-all
  redis:
    database: 0
    port: 6379
    password:
    jedis:
      pool:
        max-active: 400
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    timeout: 600s
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: mygroup

geek:
  name: uzdz

app:
  id: simple-spring-boot

apollo:
  meta: http://localhost:8080
