mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  config: classpath:logback-spring.xml

server:
  port: 9090

spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8899
        port: 7080
  application:
    name: simple-springboot-study-all
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 400
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    timeout: 600s

geek:
  multiple:
    datasource:
      - driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/test_01?characterEncoding=utf8
        username: root
        password: 123456
        name: user
        defaultDataSource: true
      - driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/test_02?characterEncoding=utf8
        username: root
        password: 123456
        name: member