mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  config: classpath:logback-spring.xml

server:
  port: 9092

spring:
  application:
    name: uzdz
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
      datasource:
        ds:
          nacos:
            server-addr: 10.16.154.176:31148
            dataId: uzdz-flow-rules
            groupId: SENTINEL_GROUP
            namespace: local
            rule-type: flow
  messages:
    basename: static/i8n/messages #相对路径 开头请勿添加斜杠
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
#  datasource:
#    jdbcUrl: jdbc:mysql://localhost:3306/demo?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
#    username: root
#    password: 123456
#    type: com.alibaba.druid.pool.DruidDataSource
#    driverClassName: com.mysql.jdbc.Driver
  data:
    mongodb:
      uri: mongodb://localhost:27017/study
  redis:
    database: 0
    port: 6379
    password:
    jedis:
      pool:
        max-active: 400
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    timeout: 600s
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: mygroup

geek:
  name: uzdz

app:
  id: simple-spring-boot

apollo:
  meta: http://localhost:8080

stat-view-servlet:
  enabled: true
  login-username: druid
  login-password: 123456

phoenix:
  datasource:
    jdbcUrl: jdbc:phoenix:localhost:2181
    username:
    password:
    driverClassName: org.apache.phoenix.jdbc.PhoenixDriver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      # 池中维护的最小空闲连接数
      minimum-idle: 10
      # 池中最大连接数，包括闲置和使用中的连接
      maximum-pool-size: 20
      # 此属性控制从池返回的连接的默认自动提交行为。默认为true
      auto-commit: true
      # 允许最长空闲时间
      idle-timeout: 30000
      # 此属性表示连接池的用户定义名称，主要显示在日志记录和JMX管理控制台中，以标识池和池配置。 默认值：自动生成
      pool-name: custom-hikari
      #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      # 连接测试sql 这个地方需要根据数据库方言差异而配置 例如 oracle 就应该写成  select 1 from dual
      connection-test-query: SELECT 1

elasticsearch:
  ip: 127.0.0.1:9201

qiyee:
  rocketmq:
    isEnable: false